### ISSUE TITLE
gtkspell

### ISSUE THREAD

**Issue by peanuts007** [mdrasmus/keepnote#739]
With Ubuntu 14.04 you have to use python-gtkspell instead of python-gnome2-extras. This works for me.
However as of 16.04 gtkspel has been replaced by gtkspellcheck.
There is a package python-gtkspellcheck but keepnote doesn’t supports this.

I failed to figure out how to change the calls from gtkspel to gtkspellcheck  :-(

Can somebody help. I assume it should be a smaller change and I really would love to have spell checking back.

THANX

**Comment by jjk-jacky** [comment]
So I had to deal with this recently as well, and while I'm not familiar with ether keepnote, python or gtkspell, I think I found a way to get it working again.

Seems, all that's missing is the python module for gtkspell - which used to be provided by the python-gnome2-extras package - gtkspell itself still actually being installed/available (package libgtkspell0).

So, here's how to get it - a dirty way to just get things working:
```
# install needed build deps
sudo apt-get install python-gtk2-dev libgtkspell-dev

# get source code
curl -JLO 'https://ftp.gnome.org/pub/GNOME/sources/gnome-python-extras/2.25/gnome-python-extras-2.25.3.tar.bz2'
tar xf gnome-python-extras-2.25.3.tar.bz2
cd gnome-python-extras-2.25.3
# only build the library we need
./configure
make -C gtkspell
# and place it where keepnote will find it
sudo cp gtkspell/.libs/gtkspell.so /usr/lib/python2.7/dist-packages/gtk-2.0/
```
And that should do it. Of course you still need other deps, e.g; aspell-XX & co.

Ok so since I got them, if you're lazy & don't mind trusting some guy on the Internet, here:
- 32bits : https://filebin.ca/3n8hhoEF8V7m
d3b4fcebcbcb33beb009d2d993c7a4d4924dc775  gtkspell.so

- 64bits: https://filebin.ca/3n45kVWYNDbQ
984afbca366c4b4c5c66840bc85460e60e087cbb  gtkspell.so

HTH,

**Comment by peanuts007** [comment]
Hi jjk-jacky,
I have tried your solution and I can confirm that it it perfectly working :-)
Many THANX!
